/* EDIT THIS FILE TO UPDATE THE WORDING ON EVERY PAGE. */
const content={
  home:{eyebrow:"Hi, I'm",title:"Jocelyn Zhao.",intro:"I'm a high school student exploring how engineering, research, creativity, and leadership can turn ideas into meaningful work.",note:"My interests span robotics, computational research, figure skating, and business."},
  research:{number:"01",title:"Research",intro:"I use computation and data to study questions about decision-making, technology, and society.",items:[{meta:"Computational Modeling · 2026",title:"Strategic Forgetting in Changing Markets",body:"How much of the past should an investor remember when a market keeps changing? I explored this question through random-walk simulations, parameter sweeps, analytical modeling, and data visualization.",tags:["Python","Simulation","Statistics"]},{meta:"Social Science Research",title:"AI Exposure and First-Generation Women in STEM",body:"An ongoing data-driven research project examining how occupational exposure to artificial intelligence relates to the experiences of first-generation immigrant women in STEM.",tags:["Data Analysis","Economics","AI & Society"]}]},
  skating:{number:"02",title:"Figure Skating",intro:"Ten years on the ice have taught me patience, precision, resilience, and the value of incremental progress.",items:[{meta:"U.S. Figure Skating",title:"Gold Medalist",body:"After years of training and testing, I passed the senior-level test and earned U.S. Figure Skating Gold Medalist recognition. Skating continues to shape how I approach difficult goals—one deliberate repetition at a time.",tags:["Discipline","Performance","Long-Term Growth"]}]},
  robotics:{number:"03",title:"Robotics",intro:"I enjoy turning open-ended challenges into mechanisms that can be built, tested, and improved.",items:[{meta:"FRC Robotics · Mechanical Design",title:"Design Lead",body:"I design competition-robot mechanisms through CAD, prototyping, testing, and close collaboration with other subteams. As design lead, I help move ideas from an early concept toward a reliable system.",tags:["CAD","Prototyping","Team Leadership"]},{meta:"UC Davis COSMOS · 2026",title:"Computers in Biophysics & Robotics",body:"I explored how computation can model physical and biological systems, connecting programming, probability, and robotics through collaborative projects and experiments.",tags:["Robotics","Computation","Research"]}]},
  deca:{number:"04",title:"DECA",intro:"DECA gives me a space to practice clear communication, structured problem-solving, and business thinking.",items:[{meta:"Business & Entrepreneurship",title:"Learning Through Competition",body:"Through DECA, I work on presenting ideas under pressure, analyzing business situations, and developing practical recommendations. This page will grow as I add future projects, events, and results.",tags:["Presentation","Strategy","Entrepreneurship"]}]}
};
const links=[['Home','index.html'],['Research','research.html'],['Figure Skating','figure-skating.html'],['Robotics','robotics.html'],['DECA','deca.html']];
const page=document.body.dataset.page;
document.querySelector('#site-header').innerHTML=`<nav class="nav"><a class="wordmark" href="index.html">JZ</a><button class="menu-button" aria-expanded="false" aria-controls="nav-links">Menu</button><div class="nav-links" id="nav-links">${links.map(([name,url])=>`<a href="${url}"${url.startsWith(page==='home'?'index':page==='skating'?'figure':page)?' aria-current="page"':''}>${name}</a>`).join('')}</div></nav>`;
const nav=document.querySelector('#nav-links'),button=document.querySelector('.menu-button');button.addEventListener('click',()=>{const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});
if(page==='home'){const c=content.home;document.querySelector('#page-content').innerHTML=`<section class="home-hero"><p class="eyebrow">${c.eyebrow}</p><h1>${c.title}</h1><p class="home-intro">${c.intro}</p><p class="home-note">${c.note}</p><a class="text-link" href="research.html">Explore my work <span>→</span></a></section>`}else{const c=content[page];document.querySelector('#page-content').innerHTML=`<header class="page-hero"><p class="section-number">${c.number}</p><h1>${c.title}</h1><p>${c.intro}</p></header><section class="entries">${c.items.map(item=>`<article class="entry"><p class="entry-meta">${item.meta}</p><div><h2>${item.title}</h2><p>${item.body}</p><ul>${item.tags.map(tag=>`<li>${tag}</li>`).join('')}</ul></div></article>`).join('')}</section>`}
document.querySelector('#site-footer').innerHTML=`<div class="footer"><p>© ${new Date().getFullYear()} Jocelyn Zhao</p><div><a href="mailto:jocelyn.zhao.316@gmail.com">Email</a><a href="https://github.com/jocelynzhao316" target="_blank" rel="noreferrer">GitHub</a></div></div>`;
